a = {1:'왕', 2:'감', 3:'자'}
print(a)
del a[1]
print(a)
a[1] = '맛있다'
print(a)
print(a[1])
print(a.keys())
print(list(a.keys()))
print(a.values())
print(list(a.values()))
print(a.items())
print(list(a.items()))
print(a.clear())
print(a.get(2))
print(a.get(1,'김치만두'))
a[2]= '왕감자'
print(1 in a)
print(2 in a)
t = set("hello")
print(t)
v = set("welcome")
print(v)
print(list(v&t))
print(t|v)
print(t-v)
t.add('t')
print(t)
v.update(['t', 'd'])
print(v)
